name: 'web3 archive action'
description: 'Save single page html and screenshot of url'
author: 'pawanpaudel93'
inputs:
  web3_token:
    description: 'API token for web3.storage'
    required: true
  web3_api:
    description: 'API URL'
    required: false
    default: 'https://api.web3.storage'
  url:
    description: 'url to save single page html and screenshot for.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
