name: CI
on: [workflow_dispatch]
jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v3
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
        with:
          args: 'npm run all'
